name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Adjust as needed

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run preprocessing script
      - name: Run data preprocessing
        run: |
          python -c "import pandas as pd; from src.preprocess import preprocess_data; df = pd.read_csv('data/customer_churn.csv'); preprocess_data(df)"

      # Run model training
      - name: Train model
        run: |
          python -c "from src.model import main; model.fit(X_train, y_train)"

      # Optional: Run tests or validation scripts if you have any
      # - name: Run tests
      #   run: |
      #     python -m unittest discover -s tests

      # Notify success
      - name: Notify success
        run: echo "CI pipeline completed successfully!"
